#Example of a docker-compose for ROS
networks:
  ros:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore 
    networks:
      ros:
        ipv4_address: 172.26.0.2

  rust-node:
    image: mjpc13/ros:rust-devel
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
