#Example of a docker-compose for ROS
networks:
  ros:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    environment:
      - "NGROK_TOKEN=your_token"
    networks:
      ros:
        ipv4_address: 172.26.0.2

  talker:
    image: ros:noetic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros

  listener:
    image: ros:noetic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      - ros

#Vizualization node example
  viz:
    image: ros:noetic-perception
    container_name: ros_visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    #share your user to the container in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes: 
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/<your_user>:/home/<your_user>:rw #share your home with write permissions
    command: rqt