#Example of a docker-compose for ROS
networks:
  ros:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  ros-master:
    build: .
    command: stdbuf -o L roscore
    environment:
      - "NGROK_TOKEN=<your_token>"
    networks:
      ros:
        ipv4_address: 172.26.0.2