name: build base image

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        ros_distro: [melodic, noetic]
        exclude:
          - os: ubuntu-18.04
            ros_distro: noetic
          - os: ubuntu-20.04
            ros_distro: melodic
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push the image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_PASSWORD }}/ros:${{matrix.ros_distro}}-base \
            --platform linux/amd64,linux/arm/v7,linux/arm64
            --build-arg ROS_DISTRO=${{matrix.ros_distro}} .
