name: build base image

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ros_distro: [melodic, noetic]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push the image
        run: |
          docker buildx build --push \
            --tag ${{secrets.DOCKER_USERNAME}}/ros:${{matrix.ros_distro}}-base \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --build-arg ROS_DISTRO=${{matrix.ros_distro}} .
